### Login request
POST https://extranet.qteam.be/VPLD/rest.desadv.cls?func=login
Content-Type: application/json

{
  "user": "scan",
  "password": "scan"
}

### gDeadlist

POST https://extranet.qteam.be/VPLD/rest.desadv.cls?func=gDeAdlist
Content-Type: application/json

{
  "depot": 59
  
}

### DeAdList

POST https://extranet.qteam.be/VPLD/rest.desadv.cls?func=DeAdList
Content-Type: application/json

{
  "depot": 59
  
}